[package]
name = "stac"
version = "0.0.2"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
edition = "2021"
description = "Rust library for the SpatioTemporal Asset Catalog (STAC) metadata standard"
homepage = "https://github.com/gadomski/stac-rs"
repository = "https://github.com/gadomski/stac-rs"
license = "MIT OR Apache-2.0"
keywords = ["geospatial", "stac", "metadata", "geo", "raster"]
categories = ["science", "data-structures"]

[dependencies]
chrono = "0.4"
geojson = "0.22"
reqwest = { version = "0.11", optional = true, features = ["json", "blocking"] }
path-slash = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
thiserror = "1"
url = "2"

[dev-dependencies]
assert-json-diff = "2"
tempfile = "3"

[features]
default = ["reqwest"]
