[package]
name = "stac"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
geojson = "0.22"
reqwest = { version = "0.11", optional = true, features = ["json", "blocking"] }
path-slash = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
url = "2"

[dev-dependencies]
assert-json-diff = "2"

[features]
default = ["reqwest"]
